repos:
- repo: https://github.com/ambv/black
  rev: 21.5b1
  hooks:
  - id: black
    name: black - Format code (-l 120)
    language_version: python3.7
    args: [-l 120]
- repo: local
  hooks:
  - id: mypy
    name: mypy - Check static types match
    entry: pipenv run mypy recommendation_system --ignore-missing-imports
    pass_filenames: false
    language: system
    types: [python]
 - id: pytest
    name: pytest - Check unit tests
    entry: pytest recommendation_system/ --cov -p no:warnings --doctest-modules
    pass_filenames: false
    language: system
    types: [python]